[package]
name = "application-core"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
config = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
